
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;


/**
 *
 * @author mpaze
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    public Employees() {
        initComponents();
        addEmployeeDetailsToScrollPane(jScrollPane1);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        employees1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        upload_tasks1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        manage_tasks1 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        register_workers1 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        help1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        logout1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        title1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        menuBar1.setForeground(new java.awt.Color(245, 219, 165));
        menuBar1.setToolTipText("");
        menuBar1.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 20)); // NOI18N
        menuBar1.setPreferredSize(new java.awt.Dimension(65, 50));

        menu1.setText(" MENU");
        menu1.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 26)); // NOI18N

        home.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menu1.add(home);
        menu1.add(jSeparator6);

        employees1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        employees1.setText("EMPLOYEES");
        employees1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees1ActionPerformed(evt);
            }
        });
        menu1.add(employees1);
        menu1.add(jSeparator7);

        upload_tasks1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        upload_tasks1.setText("UPLOAD TASKS");
        upload_tasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_tasks1ActionPerformed(evt);
            }
        });
        menu1.add(upload_tasks1);
        menu1.add(jSeparator9);

        manage_tasks1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        manage_tasks1.setText("MANAGE TASKS");
        manage_tasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_tasks1ActionPerformed(evt);
            }
        });
        menu1.add(manage_tasks1);
        menu1.add(jSeparator10);

        register_workers1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        register_workers1.setText("REGISTER WORKERS");
        register_workers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_workers1ActionPerformed(evt);
            }
        });
        menu1.add(register_workers1);
        menu1.add(jSeparator11);

        help1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        help1.setText("HELP");
        help1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1ActionPerformed(evt);
            }
        });
        menu1.add(help1);
        menu1.add(jSeparator8);

        logout1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        logout1.setText("LOGOUT");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        menu1.add(logout1);

        menuBar1.add(menu1);

        jMenu2.setText("                                                                                                                                                      ");
        jMenu2.setEnabled(false);
        menuBar1.add(jMenu2);

        title1.setText("SKY CODE");
        title1.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 48)); // NOI18N
        menuBar1.add(title1);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

    }//GEN-LAST:event_homeActionPerformed

    private void employees1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees1ActionPerformed
        Employees empolyees = new Employees();

        empolyees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employees1ActionPerformed

    private void upload_tasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_tasks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upload_tasks1ActionPerformed

    private void manage_tasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_tasks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_tasks1ActionPerformed

    private void register_workers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_workers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_register_workers1ActionPerformed

    private void help1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_help1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1ActionPerformed
   
private ResultSet getEmployeeDetails() {
    try {
        Connection conn = DatabaseHelper.connect();
        String sql = "SELECT id, name, lastname, email, phone_num, address, salary, department FROM register";
        PreparedStatement statement = conn.prepareStatement(sql);
        return statement.executeQuery();
    } catch (SQLException ex) {
        ex.printStackTrace();
        return null;
    }
}
// Method to add employee details to JScrollPane
private void addEmployeeDetailsToScrollPane(JScrollPane scrollPane) {
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
    Font customFont = new Font("Verdana", Font.PLAIN, 10); // Smaller font size

    try {
        ResultSet resultSet = getEmployeeDetails();
        if (resultSet != null) {
            // Creating the header row
            JPanel headerPanel = new JPanel(new GridBagLayout());
            headerPanel.setBackground(Color.LIGHT_GRAY);

            GridBagConstraints gbc = new GridBagConstraints();
            gbc.insets = new Insets(0, 0, 0, 0); // No padding

            addHeaderCell(headerPanel, gbc, "ID", customFont, 0);
            addHeaderCell(headerPanel, gbc, "Name", customFont, 1);
            addHeaderCell(headerPanel, gbc, "Last Name", customFont, 2);
            addHeaderCell(headerPanel, gbc, "Email", customFont, 3);
            addHeaderCell(headerPanel, gbc, "Phone", customFont, 4);
            addHeaderCell(headerPanel, gbc, "Address", customFont, 5);
            addHeaderCell(headerPanel, gbc, "Salary", customFont, 6);
            addHeaderCell(headerPanel, gbc, "Department", customFont, 7);

            panel.add(headerPanel);

            while (resultSet.next()) {
                JPanel employeePanel = new JPanel(new GridBagLayout());
                employeePanel.setBackground(Color.WHITE);

                addDataCell(employeePanel, gbc, String.valueOf(resultSet.getInt("id")), customFont, 0);
                addDataCell(employeePanel, gbc, resultSet.getString("name"), customFont, 1);
                addDataCell(employeePanel, gbc, resultSet.getString("lastname"), customFont, 2);
                addDataCell(employeePanel, gbc, resultSet.getString("email"), customFont, 3);
                addDataCell(employeePanel, gbc, resultSet.getString("phone_num"), customFont, 4);
                addDataCell(employeePanel, gbc, resultSet.getString("address"), customFont, 5);
                addDataCell(employeePanel, gbc, String.valueOf(resultSet.getDouble("salary")), customFont, 6);
                addDataCell(employeePanel, gbc, resultSet.getString("department"), customFont, 7);

                panel.add(employeePanel);
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }

    panel.setBackground(Color.WHITE);
    scrollPane.setViewportView(panel);
}

private void addHeaderCell(JPanel panel, GridBagConstraints gbc, String text, Font font, int gridx) {
    gbc.gridx = gridx;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    
    JLabel label = new JLabel(text);
    label.setFont(font);
    label.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // No padding
    panel.add(label, gbc);
}

private void addDataCell(JPanel panel, GridBagConstraints gbc, String text, Font font, int gridx) {
    gbc.gridx = gridx;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    
    JLabel label = new JLabel(text);
    label.setFont(font);
    label.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // No padding
    panel.add(label, gbc);
}


// Helper method to create header labels
private JLabel createHeaderLabel(String text, Font font) {
    JLabel label = new JLabel(text);
    label.setFont(font);
    label.setForeground(Color.BLACK);
    return label;
}

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem employees1;
    private javax.swing.JMenuItem help1;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem logout1;
    private javax.swing.JMenuItem manage_tasks1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuItem register_workers1;
    private javax.swing.JMenu title1;
    private javax.swing.JMenuItem upload_tasks1;
    // End of variables declaration//GEN-END:variables
}
