
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mpaze
 */
public class UploadTasks extends javax.swing.JFrame {

    /**
     * Creates new form UploadTasks
     */
    public UploadTasks() {
        initComponents();
        populateEmployeeComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskDescriptionArea = new javax.swing.JTextArea();
        insertButton = new javax.swing.JButton();
        messageText = new javax.swing.JLabel();
        taskNameField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        deadlineField = new javax.swing.JTextField();
        menuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        employees1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        upload_tasks1 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        manage_tasks1 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        register_workers1 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        help1 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        logout1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        title1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPLOAD TASKS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));

        jLabel1.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Create New Task");

        jLabel2.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        jLabel2.setText("Task Name");

        jLabel3.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        jLabel3.setText("Task Description");

        jLabel4.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        jLabel4.setText("Worker");

        jLabel5.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        jLabel5.setText("Dead-Line");

        taskDescriptionArea.setColumns(20);
        taskDescriptionArea.setFont(new java.awt.Font("Verdana Pro", 0, 19)); // NOI18N
        taskDescriptionArea.setRows(5);
        taskDescriptionArea.setToolTipText("Task Descpription");
        jScrollPane1.setViewportView(taskDescriptionArea);

        insertButton.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        insertButton.setText("Upload");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        messageText.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        taskNameField.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        taskNameField.setToolTipText("Task Name");
        taskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameFieldActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Verdana Pro", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        deadlineField.setFont(new java.awt.Font("Verdana Pro", 0, 24)); // NOI18N
        deadlineField.setToolTipText("YYYY-MM-DD");
        deadlineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deadlineField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(375, 375, 375))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(453, 453, 453))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        menuBar1.setForeground(new java.awt.Color(245, 219, 165));
        menuBar1.setToolTipText("");
        menuBar1.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 20)); // NOI18N
        menuBar1.setPreferredSize(new java.awt.Dimension(65, 50));

        menu1.setText(" MENU");
        menu1.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 26)); // NOI18N

        home.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menu1.add(home);
        menu1.add(jSeparator6);

        employees1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        employees1.setText("EMPLOYEES");
        employees1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees1ActionPerformed(evt);
            }
        });
        menu1.add(employees1);
        menu1.add(jSeparator7);

        upload_tasks1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        upload_tasks1.setText("UPLOAD TASKS");
        upload_tasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_tasks1ActionPerformed(evt);
            }
        });
        menu1.add(upload_tasks1);
        menu1.add(jSeparator9);

        manage_tasks1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        manage_tasks1.setText("MANAGE TASKS");
        manage_tasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_tasks1ActionPerformed(evt);
            }
        });
        menu1.add(manage_tasks1);
        menu1.add(jSeparator10);

        register_workers1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        register_workers1.setText("REGISTER WORKERS");
        register_workers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_workers1ActionPerformed(evt);
            }
        });
        menu1.add(register_workers1);
        menu1.add(jSeparator11);

        help1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        help1.setText("HELP");
        help1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1ActionPerformed(evt);
            }
        });
        menu1.add(help1);
        menu1.add(jSeparator8);

        logout1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        logout1.setText("LOGOUT");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        menu1.add(logout1);

        menuBar1.add(menu1);

        jMenu2.setText("                                                                                                                               ");
        jMenu2.setEnabled(false);
        menuBar1.add(jMenu2);

        title1.setText("SKY CODE");
        title1.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 48)); // NOI18N
        menuBar1.add(title1);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        AdminHomePage adminhomepage = new AdminHomePage();

        adminhomepage.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_homeActionPerformed

    private void employees1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees1ActionPerformed
        Employees empolyees = new Employees();

        empolyees.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employees1ActionPerformed

    private void upload_tasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_tasks1ActionPerformed

        UploadTasks uploadtasks = new UploadTasks();

        this.setVisible(false);
        uploadtasks.setVisible(true);
    }//GEN-LAST:event_upload_tasks1ActionPerformed

    private void manage_tasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_tasks1ActionPerformed
        ManageTasks managetasks = new ManageTasks();

        managetasks.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manage_tasks1ActionPerformed

    private void register_workers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_workers1ActionPerformed
       Register register = new Register();
        
        this.dispose();
        register.setVisible(true);
    }//GEN-LAST:event_register_workers1ActionPerformed

    private void help1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1ActionPerformed
        HelpAdmin helpadmin = new HelpAdmin();
        helpadmin.setVisible(true);
    }//GEN-LAST:event_help1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        Main main = new Main();

        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout1ActionPerformed

    private void taskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskNameFieldActionPerformed

    private void deadlineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlineFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed

        String taskName = taskNameField.getText();
        String taskDescription = taskDescriptionArea.getText();
        String userIdString = jComboBox1.getSelectedItem().toString(); 
        String deadline = deadlineField.getText();

        // Checking if any field is empty
        if (taskName.isEmpty() || taskDescription.isEmpty() || userIdString.isEmpty() || deadline.isEmpty()) {
            messageText.setText("Please fill in all fields.");
            return;
        }

        try {
            Connection conn = DatabaseHelper.connect();

            // Checking if the date format is correct
            if (!isValidDateFormat(deadline)) {
                messageText.setText("Incorrect date format. Please use YYYY-MM-DD.");
                return;
            }

            // Extracting the ID part from the string "27 - Mikey Mouse"
            String userId = userIdString.split(" - ")[0]; // Spliting the string by " - " and take the first part (the ID)

            String sql = "INSERT INTO tasks (taskname, task_description, user_id, deadline_date) VALUES (?, ?, ?, ?)";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, taskName);
            statement.setString(2, taskDescription);
            statement.setInt(3, Integer.parseInt(userId)); 
            statement.setString(4, deadline);
            statement.executeUpdate();
            messageText.setText("Task inserted successfully!");
        } catch (SQLException ex) {
            messageText.setText("An error occurred while inserting the task.");
            ex.printStackTrace();
        } catch (NumberFormatException ex) {
            messageText.setText("Invalid user ID format.");
            ex.printStackTrace();
        }


    }//GEN-LAST:event_insertButtonActionPerformed

    // Method to check if the date format is valid
    private boolean isValidDateFormat(String date) {
        return date.matches("\\d{4}-\\d{2}-\\d{2}");
    }

       
     // Method to populate JComboBox with employee details
    private void populateEmployeeComboBox() {
        try (Connection conn = DatabaseHelper.connect()) {
            String sql = "SELECT id, name, lastname FROM register";
            try (PreparedStatement statement = conn.prepareStatement(sql);
                 ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    int id = resultSet.getInt("id");
                    String name = resultSet.getString("name");
                    String lastName = resultSet.getString("lastname");

                    // Add formatted string to JComboBox
                    jComboBox1.addItem(id + " - " + name + " " + lastName);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deadlineField;
    private javax.swing.JMenuItem employees1;
    private javax.swing.JMenuItem help1;
    private javax.swing.JMenuItem home;
    private javax.swing.JButton insertButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem logout1;
    private javax.swing.JMenuItem manage_tasks1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JLabel messageText;
    private javax.swing.JMenuItem register_workers1;
    private javax.swing.JTextArea taskDescriptionArea;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JMenu title1;
    private javax.swing.JMenuItem upload_tasks1;
    // End of variables declaration//GEN-END:variables
}
