
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javafx.scene.control.DatePicker;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mpaze
 */
public class UserHomePage extends javax.swing.JFrame {

    /**
     * Creates new form UserHomePage
     */
    public UserHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasks = new javax.swing.JButton();
        report = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        calendar = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        menu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setPreferredSize(new java.awt.Dimension(1400, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        tasks.setBackground(new java.awt.Color(0, 0, 0));
        tasks.setFont(new java.awt.Font("Verdana Pro", 1, 22)); // NOI18N
        tasks.setText("TASKS - PROJECTS");
        tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksActionPerformed(evt);
            }
        });
        getContentPane().add(tasks);
        tasks.setBounds(90, 170, 270, 120);

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setFont(new java.awt.Font("Verdana Pro", 1, 22)); // NOI18N
        report.setText("VIEW REPORT");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report);
        report.setBounds(90, 390, 270, 120);

        contact.setBackground(new java.awt.Color(0, 0, 0));
        contact.setFont(new java.awt.Font("Verdana Pro", 1, 22)); // NOI18N
        contact.setText("CONTACT");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        getContentPane().add(contact);
        contact.setBounds(90, 610, 270, 120);

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 1, 24)); // NOI18N
        calendar.setEnabled(false);
        calendar.setOpaque(true);
        getContentPane().add(calendar);
        calendar.setBounds(1040, 210, 240, 140);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        calendar.setText(LocalDateTime.now().format(formatter));

        background_img.setBackground(new java.awt.Color(0, 0, 0));
        background_img.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        background_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img4.png"))); // NOI18N
        background_img.setText("jLabel1");
        background_img.setToolTipText("");
        getContentPane().add(background_img);
        background_img.setBounds(-110, -10, 1590, 840);

        menuBar.setForeground(new java.awt.Color(245, 219, 165));
        menuBar.setToolTipText("");
        menuBar.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 20)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(65, 50));

        home.setText("MENU");
        home.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 26)); // NOI18N

        menu.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        menu.setText("HOME");
        home.add(menu);
        home.add(jSeparator1);

        logout.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        home.add(logout);

        menuBar.add(home);

        jMenu1.setText("                                                                                                                                                                              ");
        jMenu1.setEnabled(false);
        menuBar.add(jMenu1);

        jMenu3.setText("SKY CODE");
        jMenu3.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 48)); // NOI18N
        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksActionPerformed
       
          Tasks tasks = new Tasks();
          
          this.setVisible(false);
          tasks.setVisible(true);
        
    }//GEN-LAST:event_tasksActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        Main main = new Main();
        
        main.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logoutActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_img;
    private javax.swing.JLabel calendar;
    private javax.swing.JButton contact;
    private javax.swing.JMenu home;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton report;
    private javax.swing.JButton tasks;
    // End of variables declaration//GEN-END:variables
}
