
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mpaze
 */
public class ViewReport extends javax.swing.JFrame {

    /**
     * Creates new form ViewReport
     */
    public ViewReport() {
        initComponents();
        addTaskDetailsToScrollPane(jScrollPane1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewreport_label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        tasks = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        contact = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        logout = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        title = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        viewreport_label.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 36)); // NOI18N
        viewreport_label.setText("VIEW REPORT");

        jPanel2.setBackground(new java.awt.Color(219, 239, 239));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addComponent(viewreport_label)
                .addGap(512, 512, 512))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(viewreport_label)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        menuBar.setForeground(new java.awt.Color(245, 219, 165));
        menuBar.setToolTipText("");
        menuBar.setFont(new java.awt.Font("Verdana Pro Cond Black", 0, 20)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(65, 50));

        menu.setText(" MENU");
        menu.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 26)); // NOI18N

        home.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menu.add(home);
        menu.add(jSeparator3);

        tasks.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        tasks.setText("TASKS");
        tasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksActionPerformed(evt);
            }
        });
        menu.add(tasks);
        menu.add(jSeparator1);

        jMenuItem1.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        jMenuItem1.setText("VIEW REPORT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem1);
        menu.add(jSeparator4);

        contact.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        contact.setText("HELP");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        menu.add(contact);
        menu.add(jSeparator2);

        logout.setFont(new java.awt.Font("Verdana Pro", 0, 16)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);

        menuBar.add(menu);

        jMenu4.setText("                                                                                                                                                      ");
        jMenu4.setEnabled(false);
        menuBar.add(jMenu4);

        title.setText("SKY CODE");
        title.setFont(new java.awt.Font("Verdana Pro Semibold", 0, 48)); // NOI18N
        menuBar.add(title);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

        UserHomePage userhomepage = new UserHomePage();

        userhomepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void tasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksActionPerformed
        Tasks tasks = new Tasks();

        this.setVisible(false);
        tasks.setVisible(true);
    }//GEN-LAST:event_tasksActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        ViewReport viewreport = new ViewReport();

        this.setVisible(false);
        viewreport.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        Help help = new Help();

        help.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_contactActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

        Main main = new Main();

        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

       private ResultSet getTaskDetails() {
    try {
        Connection conn = DatabaseHelper.connect();
        String sql = "SELECT tasks.*, register.name FROM tasks JOIN register ON tasks.user_id = register.id";
        PreparedStatement statement = conn.prepareStatement(sql);
        return statement.executeQuery();
    } catch (SQLException ex) {
        ex.printStackTrace();
        return null;
    }
}

    // Method to add task details to JScrollPane
    private void addTaskDetailsToScrollPane(JScrollPane scrollPane) {

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        Font customFont = new Font("Verdana pro", Font.PLAIN, 18);

        try {
            ResultSet resultSet = getTaskDetails();
            if (resultSet != null) {
                while (resultSet.next()) {
                    String taskName = resultSet.getString("taskname");
                    String taskDescription = resultSet.getString("task_description");
                    String userName = resultSet.getString("name");
                    String deadline = resultSet.getString("deadline_date");
                    String fileName = resultSet.getString("file_path");
                    String reportText = resultSet.getString("report_text"); 

                    // JPanel for each task detail
                    JPanel taskPanel = new JPanel();
                    taskPanel.setLayout(new BoxLayout(taskPanel, BoxLayout.Y_AXIS));
                    taskPanel.setBackground(Color.WHITE);
                    taskPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

                    JLabel taskLabel = new JLabel("Task: " + taskName);
                    taskLabel.setFont(customFont);

                    JLabel descriptionLabel = new JLabel("Description: " + taskDescription);
                    descriptionLabel.setFont(customFont);

                    JLabel userLabel = new JLabel("Assigned to: " + userName);
                    userLabel.setFont(customFont);

                    JLabel deadlineLabel = new JLabel("Deadline: " + deadline);
                    deadlineLabel.setFont(customFont);
                    
                    JLabel filepath1 = new JLabel("File path to: " + fileName);
                    filepath1.setFont(customFont);

                    JLabel report1 = new JLabel("Report: " + reportText);
                    report1.setFont(customFont);
                    
                   
                    // Adding labels to task JPanel
                    taskPanel.add(taskLabel);
                    taskPanel.add(descriptionLabel);
                    taskPanel.add(userLabel);
                    taskPanel.add(deadlineLabel);
                    taskPanel.add(filepath1);
                    taskPanel.add(report1);
                    
                    

                    // Adding task JPanel to the main panel
                    panel.add(taskPanel);

                    // Small gap after each taskPanel
                    panel.add(Box.createRigidArea(new Dimension(0, 10))); // 10 pixels vertical gap
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        panel.setBackground(Color.WHITE);

        scrollPane.setViewportView(panel);
    }

    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem contact;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem tasks;
    private javax.swing.JMenu title;
    private javax.swing.JLabel viewreport_label;
    // End of variables declaration//GEN-END:variables
}
